# NOTE: Generated By HttpRunner v4.3.0
# FROM: course2\course2_login.yaml
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseCourse2Login(HttpRunner):

    config = (
        Config("登录测试用例")
        .variables(**{"account": "auto", "psw": "sdfsdfsdf", "code": 0})
        .base_url("${ENV(base_url)}")
        .verify(False)
        .export(*["cookie"])
    )

    teststeps = [
        Step(
            RunRequest("login")
            .post("/api/mgr/loginReq")
            .with_data({"username": "$account", "password": "$psw"})
            .extract()
            .with_jmespath("body.retcode", "retcode")
            .with_jmespath("cookies.sessionid", "cookie")
            .validate()
            .assert_equal("$retcode", "$code")
        ),
    ]


if __name__ == "__main__":
    TestCaseCourse2Login().test_start()
