# NOTE: Generated By HttpRunner v4.3.0
# FROM: .\course2\demo1_addcourse.yaml
import pytest

from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import Parameters
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from course2.course2_login_test import TestCaseCourse2Login as Course2Login


class TestCaseDemo1Addcourse(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"name-desc-idx": "${add_course_variables()}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("添加课程")
        .base_url("${ENV(base_url)}")
        .verify(False)
        .export(*["cookie", "course_id"])
    )

    teststeps = [
        Step(RunTestCase("login").call(Course2Login).export(*["cookie"])),
        Step(
            RunRequest("addcourse")
            .post("/api/mgr/sq_mgr/")
            .with_headers(**{"Content-Type": "application/x-www-form-urlencoded"})
            .with_cookies(**{"sessionid": "$cookie"})
            .with_data(
                {
                    "action": "add_course",
                    "data": '{"name":"${name}","desc":"${desc}", "display_idx":"${idx}"}',
                }
            )
            .extract()
            .with_jmespath("body.id", "course_id")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.retcode", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo1Addcourse().test_start()
