# Generated by Django 4.1.3 on 2022-11-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('address', models.CharField(max_length=256)),
                ('limits', models.IntegerField(default=100)),
                ('status', models.BooleanField(default=True)),
                ('createTime', models.DateTimeField(null=True)),
            ],
        ),
    ]
