# Generated by Django 4.1.3 on 2022-11-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='updateTime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='createTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
