# Generated by Django 4.1.3 on 2022-11-23 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0002_event_updatetime_alter_event_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sgin.event')),
            ],
        ),
    ]
