# Generated by Django 4.1.3 on 2022-11-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgin', '0004_guest_is_sgin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='startTime',
            field=models.DateTimeField(null=True),
        ),
    ]
