# NOTE: Generated By HttpRunner v4.3.0
# FROM: testcase\project1_case001.json
from httprunner import HttpRunner, Config, Step, RunRequest


class TestCaseProject1Case001(HttpRunner):

    config = Config("case001").base_url("http://localhost")

    teststeps = [
        Step(
            RunRequest("step001")
            .get("/demo2")
            .with_params(**{"age": 66, "addr": "nanjing", "name": "哈哈哈"})
        ),
    ]


if __name__ == "__main__":
    TestCaseProject1Case001().test_start()
