# Generated by Django 4.1.4 on 2022-12-20 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="config",
            old_name="base_rul",
            new_name="base_url",
        ),
    ]
