# Generated by Django 4.1.4 on 2023-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0002_case_create_by_case_update_by_config_create_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "开发中"), (1, "维护中"), (2, "稳定运行")],
                default=2,
                verbose_name="项目状态",
            ),
        ),
    ]
