# Generated by Django 4.1.4 on 2023-02-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0003_alter_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.SmallIntegerField(
                choices=[(0, "开发"), (1, "测试"), (2, "运维"), (3, "项目经理")],
                default=1,
                verbose_name="用户类型",
            ),
        ),
    ]
