# Generated by Django 4.1.4 on 2023-03-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0005_config_project"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["sorted_no", "id"]},
        ),
        migrations.AddField(
            model_name="step",
            name="sorted_no",
            field=models.PositiveSmallIntegerField(default=1, verbose_name="步骤顺序"),
        ),
        migrations.AlterField(
            model_name="config",
            name="name",
            field=models.CharField(max_length=128, verbose_name="用例名称"),
        ),
        migrations.AlterField(
            model_name="request",
            name="step",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="request",
                to="sqtp.step",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="step",
            unique_together={("belong_case", "sorted_no")},
        ),
    ]
