# Generated by Django 4.1.4 on 2023-07-04 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0006_alter_step_options_step_sorted_no_alter_config_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="step",
            options={"ordering": ["id", "sorted_no"]},
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="创建时间"
                    ),
                ),
                (
                    "update_time",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("desc", models.TextField(blank=True, null=True, verbose_name="描述")),
                (
                    "name",
                    models.CharField(max_length=32, unique=True, verbose_name="计划名称"),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(3, "已执行"), (1, "执行中"), (2, "中断"), (0, "未执行")],
                        default=0,
                        verbose_name="计划状态",
                    ),
                ),
                (
                    "exec_counts",
                    models.PositiveSmallIntegerField(default=0, verbose_name="执行次数"),
                ),
                (
                    "cases",
                    models.ManyToManyField(
                        blank=True, to="sqtp.case", verbose_name="测试用例"
                    ),
                ),
                (
                    "create_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_create_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="sqtp.environment",
                        verbose_name="测试环境",
                    ),
                ),
                (
                    "executor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行者",
                    ),
                ),
                (
                    "update_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_update_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="更新者",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "abstract": False,
            },
        ),
    ]
