# Generated by Django 4.1.4 on 2023-07-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sqtp", "0007_alter_step_options_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "未执行"), (2, "中断"), (1, "执行中"), (3, "已执行")],
                default=0,
                verbose_name="计划状态",
            ),
        ),
    ]
