# NOTE: Generated By HttpRunner v4.3.0
# FROM: .\course1\demo2_listcourse.yaml
from httprunner import HttpRunner, Config, Step, RunRequest
from httprunner import RunTestCase

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from course1.demo1_login_test import TestCaseDemo1Login as Demo1Login


class TestCaseDemo2Listcourse(HttpRunner):

    config = Config("列出课程").base_url("http://localhost").verify(False)

    teststeps = [
        Step(RunTestCase("login").call(Demo1Login).export(*["cookie"])),
        Step(
            RunRequest("list_course")
            .get("/api/mgr/sq_mgr/")
            .with_params(**{"action": "list_course", "pagenum": 1, "pagesize": 20})
            .with_cookies(**{"sessionid": "$cookie"})
            .extract()
            .with_jmespath("body.retcode", "retcode")
            .with_jmespath("body.total", "total")
            .validate()
            .assert_equal("$retcode", 0)
            .assert_equal("$total", 2)
        ),
    ]


if __name__ == "__main__":
    TestCaseDemo2Listcourse().test_start()
